version: '3.8'

services:
  node-app:
    build: 
      context: ./back-end
      dockerfile: Dockerfile
    image: node-app
    environment:
      - DB_HOST=mysql
      - DB_USERNAME=root
      - DB_PASSWORD=my-secret-pw
      - DB_NAME=my-database
      - DB_DIALECT=mysql
    ports:
      - '3000:3000'
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./back-end:/usr/src/node-app
      - /usr/src/node-app/node_modules
    networks:
      - node-network

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=my-database
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - node-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    volumes:
      - ./front-end:/app
      - /app/node_modules
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
